"""
Guards `requirements.txt` against drifting from `requirements.in`.

A lockfile does not fail loudly when it goes stale. It keeps installing an
old, valid, reproducible set that no longer matches what the spec asks for —
so someone adds a dependency, forgets to recompile, and the import error
shows up on the deploy rather than in the pull request.

Deliberately offline and deterministic. It does NOT re-resolve against PyPI:
a check that re-resolves goes red because a dependency published a release,
which turns an unrelated pull request into a false alarm and teaches everyone
to ignore the job. This asks only the question whose answer cannot change on
its own: does the lock pin every package the spec names, with hashes?
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
SPEC = HERE / "requirements.in"
LOCK = HERE / "requirements.txt"

# "uvicorn[standard]>=0.32" -> "uvicorn"; also handles ==, ~=, bare names.
_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def normalise(name: str) -> str:
    """PEP 503: underscores, hyphens and dots are equivalent."""
    return re.sub(r"[-_.]+", "-", name).lower()


def spec_names(text: str) -> set[str]:
    out: set[str] = set()
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or line.startswith("-"):
            continue
        m = _NAME.match(line)
        if m:
            out.add(normalise(m.group(1)))
    return out


def lock_pins(text: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#") or "==" not in stripped:
            continue
        m = _NAME.match(stripped)
        if not m:
            continue
        version = stripped.split("==", 1)[1].split()[0].strip("\\ ")
        out[normalise(m.group(1))] = version
    return out


def main() -> int:
    for p in (SPEC, LOCK):
        if not p.exists():
            print(f"check_lock: missing {p.name}", file=sys.stderr)
            return 1

    spec_text = SPEC.read_text()
    lock_text = LOCK.read_text()

    problems: list[str] = []

    # 1. The lock must say it came from the spec. Catches a hand-written
    #    requirements.txt masquerading as generated.
    if SPEC.name not in lock_text:
        problems.append(
            f"{LOCK.name} does not reference {SPEC.name}; it may have been hand-edited "
            f"rather than generated by pip-compile"
        )

    # 2. Every package the spec names must be pinned in the lock.
    pins = lock_pins(lock_text)
    for name in sorted(spec_names(spec_text)):
        if name not in pins:
            problems.append(
                f"{name} is in {SPEC.name} but not pinned in {LOCK.name} — recompile"
            )

    # 3. Hashes must be present, or --require-hashes silently buys nothing.
    if "--hash=sha256:" not in lock_text:
        problems.append(
            f"{LOCK.name} has no hashes; recompile with --generate-hashes"
        )

    # 4. Nothing may be left unpinned.
    for line in lock_text.splitlines():
        s = line.split("#", 1)[0].strip()
        if not s or s.startswith(("-", "\\")) or s.startswith("--hash"):
            continue
        if _NAME.match(s) and "==" not in s:
            problems.append(f"{LOCK.name} has an unpinned requirement: {s!r}")

    if problems:
        print("check_lock: FAIL", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    print(f"check_lock: ok — {len(pins)} packages pinned with hashes, spec fully covered")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
