import type { LicenseClass } from './types';

/**
 * RULE 2, RESOLVED FROM WHAT ACTUALLY SERVED THE REQUEST.
 *
 * Only `open_weight` provenance may train Shamwari Mind. Anthropic's and
 * OpenAI's terms bar using their outputs to train a competing model; Kimi
 * K3's and Qwen's permit it.
 *
 * `router.ts` stamps a licenceClass on the tier the Worker *asks for*. That
 * is the right place for intent and it is not sufficient on its own,
 * because the model that answers is not always the model that was asked
 * for:
 *
 *   - `infer()` degrades to Workers AI when both the AI Gateway and the
 *     direct provider are unreachable. That path already reported a
 *     provider of `workers-ai` while the conversation kept the licenceClass
 *     of the tier that was requested.
 *   - An AI Gateway **dynamic route** can pick a different model entirely.
 *     Editing a route is a dashboard action: no code review, no deploy. A
 *     route that fails over from Kimi to a restricted model would have
 *     written `open_weight` rows generated by a model whose terms forbid
 *     exactly that use.
 *
 * So provenance is resolved here, from the `provider/model` pair the
 * response says served the request, against an allowlist that lives in
 * code — for the same reason `licenseClass` is not in
 * `routing-policy.json`: provenance must not be editable without review.
 *
 * Unknown pairs resolve to `restricted`. An unlisted model is a model whose
 * terms nobody has read. A lost training row is recoverable; a corpus that
 * has to be thrown away, or a licence claim that cannot be defended, is
 * not.
 */
const OPEN_WEIGHT: ReadonlySet<string> = new Set<string>([
  // Moonshot Kimi K3. Bespoke licence, broadly permissive, permits training
  // on outputs. Read the LICENSE file before adding a new variant here —
  // the MaaS and attribution thresholds are revenue-scaled.
  'moonshot/kimi-k3',
  'moonshot/kimi-k3-0711-preview',

  // Alibaba Qwen, via DashScope. Tongyi Qianwen licence permits it.
  'qwen/qwen3.8-max',
  'qwen/qwen3-30b-a3b-fp8',

  // Workers AI last-resort fallback. Same Qwen weights, Cloudflare-hosted.
  `workers-ai/${'@cf/qwen/qwen3-30b-a3b-fp8'}`,
]);

/**
 * The Workers AI fallback model, named once.
 *
 * This used to be reported as the model string `fallback`, which meant
 * `platform.usageEvents` could not tell you which model answered when both
 * providers were down — and left nothing for the allowlist above to key on.
 */
export const WORKERS_AI_FALLBACK_MODEL = '@cf/qwen/qwen3-30b-a3b-fp8';

/** Normalised so casing or padding from a provider header cannot miss. */
function key(provider: string, model: string): string {
  return `${provider.trim()}/${model.trim()}`.toLowerCase();
}

/**
 * Resolve provenance from the model that actually generated the text.
 *
 * Fails closed. Callers must use this rather than `Target.licenseClass`
 * when stamping a row that the Mind training pipeline could read.
 */
export function resolveLicenseClass(provider: string, model: string): LicenseClass {
  if (OPEN_WEIGHT.has(key(provider, model))) return 'open_weight';
  // Visible on purpose: an unlisted model quietly losing its training rows
  // is the failure this whole module exists to make loud.
  console.warn('provenance: unlisted model, stamping restricted', key(provider, model));
  return 'restricted';
}

/** Exposed for the test that pins the allowlist. */
export const openWeightModels: readonly string[] = [...OPEN_WEIGHT];
